language: python

os:
- linux

python:
- '3.7'
- '3.8'

install:
- pip install -r requirements.txt

script:
- pylint --rcfile=pymultimatic/.pylintrc pymultimatic
- pycodestyle pymultimatic
- mypy --strict pymultimatic
- pylint --rcfile=tests/.pylintrc tests
- pycodestyle tests
- mypy --strict --ignore-missing-import tests
- coverage run --source=pymultimatic setup.py pytest
after_success:
- coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Wr++M3trjROBD0ond4gaOu/UcyeF38qGNby7GYAMSaQdh1WMfkgNfmfpMMlcDLn8Adc/ncn4LyqKVKsxa0Op27ht8/1JSa72mhcOOXQK0EI+gMIhNfzscSQVSx99RHTvVzJjNkjvFo0Za3jfyvqPZu0StjbAsoXmudh23D8dn36wvkGfk5zPlcqdQaA4MCTNDiCqS9aWsY9Se9/Ys4mJRg98TodesGbxvVQg4XKwckrLrABEEqdqPGey07FzzCQ0Z8mLjC7SRk+JpSnr1uY0iUWCqNA0yerZddVj1OdTByMoFGwll5NN+3RIKev6m55lb6CLj5UYDJmUWizcbs6s6BnXz6b7rqEiBqji+zNfx11HZrpJBX+wQ/pzDIm6cK7HLXKt314uARP/wXKVi0WEtHzfY5l2jdMZrGfPblMjiOu/wibJYD5vzjvWsFpYuFe+6Rak3aFTYkBaXOkJGFhl9oYX4l9V1Zb7isVSVco+OuAYuJ0tM6XRGn4GJ9EfvVflOdQaXMoVnBPO+R4Qe0ox502lISKe5rxPUllweL9UFJUleIHhgi1BxBNk/Hfbq5hksjKuHjrMAiOJCFRMtegTy48A37tvtUsoAjPwInRLI4oevGhnQPpw8Xzy+owm/pZAyUPF3nvmRHCYZG/tEawOkPTQo3Uv+zx5Rw9rhUDyN5w="
  distributions: "sdist"
  skip_existing: true
  on:
    tags: true
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change